/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package responsiveform;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IlyésBorbála(SZOFT_2
 */
public class Olalbeállítás extends javax.swing.JFrame {

    /**
     * Creates new form Olalbeállítás
     */
    public Olalbeállítás() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlPapir = new javax.swing.JPanel();
        lblMeret = new javax.swing.JLabel();
        cmbbPapirMeret = new javax.swing.JComboBox<>();
        lblForras = new javax.swing.JLabel();
        cmbbForras = new javax.swing.JComboBox<>();
        pnlTajolas = new javax.swing.JPanel();
        rbnAllo = new javax.swing.JRadioButton();
        rbtFekvo = new javax.swing.JRadioButton();
        pnlMargok = new javax.swing.JPanel();
        lblBal = new javax.swing.JLabel();
        lblFelso = new javax.swing.JLabel();
        lblJobb = new javax.swing.JLabel();
        lblAlso = new javax.swing.JLabel();
        txtfldBal = new javax.swing.JTextField();
        txtfldJobb = new javax.swing.JTextField();
        txtfldFelso = new javax.swing.JTextField();
        txtfldAlso = new javax.swing.JTextField();
        lblFejlec = new javax.swing.JLabel();
        lblLablec = new javax.swing.JLabel();
        txtfldFejlec = new javax.swing.JTextField();
        txtfldLablec = new javax.swing.JTextField();
        pnlKep = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnMégse = new javax.swing.JButton();
        lblGoogle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPapir.setBorder(javax.swing.BorderFactory.createTitledBorder("Papír"));

        lblMeret.setText("Méret");

        cmbbPapirMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A3", "A4", "A5" }));
        cmbbPapirMeret.setSelectedIndex(1);

        lblForras.setText("Forrás:");
        lblForras.setEnabled(false);

        cmbbForras.setEditable(true);
        cmbbForras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cmbbForras.setEnabled(false);

        javax.swing.GroupLayout pnlPapirLayout = new javax.swing.GroupLayout(pnlPapir);
        pnlPapir.setLayout(pnlPapirLayout);
        pnlPapirLayout.setHorizontalGroup(
            pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPapirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPapirLayout.createSequentialGroup()
                        .addComponent(lblMeret)
                        .addGap(18, 18, 18)
                        .addComponent(cmbbPapirMeret, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPapirLayout.createSequentialGroup()
                        .addComponent(lblForras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbbForras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPapirLayout.setVerticalGroup(
            pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPapirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeret, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbPapirMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForras)
                    .addComponent(cmbbForras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlTajolas.setBorder(javax.swing.BorderFactory.createTitledBorder("Tájolás"));

        buttonGroup1.add(rbnAllo);
        rbnAllo.setSelected(true);
        rbnAllo.setText("Álló");
        rbnAllo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAlloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtFekvo);
        rbtFekvo.setText("Fekvő");
        rbtFekvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFekvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTajolasLayout = new javax.swing.GroupLayout(pnlTajolas);
        pnlTajolas.setLayout(pnlTajolasLayout);
        pnlTajolasLayout.setHorizontalGroup(
            pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTajolasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnAllo)
                    .addComponent(rbtFekvo))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlTajolasLayout.setVerticalGroup(
            pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTajolasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnAllo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtFekvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMargok.setBorder(javax.swing.BorderFactory.createTitledBorder("Margók (milliméter)"));

        lblBal.setText("Bal:");

        lblFelso.setText("Felső:");

        lblJobb.setText("Jobb:");

        lblAlso.setText("Alsó:");

        txtfldBal.setText("20");

        txtfldJobb.setText("20");

        txtfldFelso.setText("25");

        txtfldAlso.setText("25");

        javax.swing.GroupLayout pnlMargokLayout = new javax.swing.GroupLayout(pnlMargok);
        pnlMargok.setLayout(pnlMargokLayout);
        pnlMargokLayout.setHorizontalGroup(
            pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMargokLayout.createSequentialGroup()
                        .addComponent(lblFelso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfldFelso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMargokLayout.createSequentialGroup()
                        .addComponent(lblBal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtfldBal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJobb, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(lblAlso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfldJobb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldAlso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlMargokLayout.setVerticalGroup(
            pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBal)
                    .addComponent(lblJobb)
                    .addComponent(txtfldBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldJobb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlso)
                    .addComponent(lblFelso)
                    .addComponent(txtfldFelso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldAlso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFejlec.setText("Fejléc:");

        lblLablec.setText("Lábléc:");

        pnlKep.setBorder(javax.swing.BorderFactory.createTitledBorder("Előlnézet"));

        jLabel9.setText("kép");

        javax.swing.GroupLayout pnlKepLayout = new javax.swing.GroupLayout(pnlKep);
        pnlKep.setLayout(pnlKepLayout);
        pnlKepLayout.setHorizontalGroup(
            pnlKepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKepLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pnlKepLayout.setVerticalGroup(
            pnlKepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKepLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOKMouseExited(evt);
            }
        });
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnMégse.setText("Mégse");
        btnMégse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMégseActionPerformed(evt);
            }
        });

        lblGoogle.setText("<html><a href=\"#\">Értékek megadása</a></html>");
        lblGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoogle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoogleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoogleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoogleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPapir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTajolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMargok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFejlec)
                            .addComponent(lblLablec))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldFejlec)
                            .addComponent(txtfldLablec))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlKep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMégse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPapir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlTajolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMargok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFejlec)
                            .addComponent(txtfldFejlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLablec)
                            .addComponent(txtfldLablec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlKep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOK)
                        .addComponent(btnMégse)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMégseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMégseActionPerformed
        //System.out.println("Mégse gombra kattintottál" + WIDTH);
        System.exit(0);
    }//GEN-LAST:event_btnMégseActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
       JOptionPane.showMessageDialog(null, "Nincsen nyomtató telepítve");
    }//GEN-LAST:event_btnOKActionPerformed

    private void lblGoogleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseClicked
        System.out.println("Labelre kattintottál()");
        try {
            Desktop.getDesktop().browse(URI.create("http://www.google.com"));
        } catch (IOException ex) {
            Logger.getLogger(Olalbeállítás.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblGoogleMouseClicked

    private void lblGoogleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseEntered
        lblGoogle.setText("<html><b><a href='#'>Érték megadása</a></b></html>");
    }//GEN-LAST:event_lblGoogleMouseEntered

    private void lblGoogleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseExited
        lblGoogle.setText("<html><a href='#'>Érték megadása</a></html>");
    }//GEN-LAST:event_lblGoogleMouseExited

    private void btnOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseEntered
        btnOK.setText("<html><b><a href='#'>OK</a></b></html>");
    }//GEN-LAST:event_btnOKMouseEntered

    private void btnOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseExited
        btnOK.setText("<html>OK</html>");
    }//GEN-LAST:event_btnOKMouseExited

    private void rbnAlloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAlloActionPerformed
        String bal = txtfldBal.getText();
        String jobb = txtfldJobb.getText();
        String felso = txtfldFelso.getText();
        String also = txtfldAlso.getText();
        txtfldBal.setText(felso);
        txtfldJobb.setText(also);
        txtfldFelso.setText(bal);
        txtfldAlso.setText(jobb);
              
        
    }//GEN-LAST:event_rbnAlloActionPerformed

    private void rbtFekvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFekvoActionPerformed
        String bal = txtfldBal.getText();
        String jobb = txtfldJobb.getText();
        String felso = txtfldFelso.getText();
        String also = txtfldAlso.getText();
        txtfldBal.setText(felso);
        txtfldJobb.setText(also);
        txtfldFelso.setText(bal);
        txtfldAlso.setText(jobb);
        
    }//GEN-LAST:event_rbtFekvoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olalbeállítás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olalbeállítás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olalbeállítás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olalbeállítás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olalbeállítás().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMégse;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbbForras;
    private javax.swing.JComboBox<String> cmbbPapirMeret;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAlso;
    private javax.swing.JLabel lblBal;
    private javax.swing.JLabel lblFejlec;
    private javax.swing.JLabel lblFelso;
    private javax.swing.JLabel lblForras;
    private javax.swing.JLabel lblGoogle;
    private javax.swing.JLabel lblJobb;
    private javax.swing.JLabel lblLablec;
    private javax.swing.JLabel lblMeret;
    private javax.swing.JPanel pnlKep;
    private javax.swing.JPanel pnlMargok;
    private javax.swing.JPanel pnlPapir;
    private javax.swing.JPanel pnlTajolas;
    private javax.swing.JRadioButton rbnAllo;
    private javax.swing.JRadioButton rbtFekvo;
    private javax.swing.JTextField txtfldAlso;
    private javax.swing.JTextField txtfldBal;
    private javax.swing.JTextField txtfldFejlec;
    private javax.swing.JTextField txtfldFelso;
    private javax.swing.JTextField txtfldJobb;
    private javax.swing.JTextField txtfldLablec;
    // End of variables declaration//GEN-END:variables
}
